### ISSUE TITLE
L10 Unable to Craft

### ISSUE THREAD

**Issue by dirckjr5335** [urnotnick/impulse-issues#102]
**Describe the bug**
Can't craft some L10 Items despite being L10 and having the crafting materials.

![20221014211723_1](https://user-images.githubusercontent.com/115851574/195962950-22337628-0503-4895-8d48-1655ca271a31.jpg)

**impulse version (press F1 in the bottom right):**
1.10.9

**Comment by SpriteCran** [comment]
found the issue, should be fixed now
