### ISSUE TITLE
/Outlandsbase does not work

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#104]
**Describe the bug**
Running the command "/outlandsbase" as OTA does not open the Hardpoint doors. Admins have been removing the doors entirely because of this.

**To reproduce**
Steps to reproduce the behaviour:
1. Join OTA
2. Transit to the Outlands Hardpoint
3. Stand near one of the doors and run the command
4. See that the door doesn't open, despite the notification in the upper right saying it has succeeded.

**Expected behaviour**
That the command will open the door as it did way back on the i17 before.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.11.0
**Lua error**
N/A

**Additional context**
N/A

**Comment by Miraak11** [comment]
Okay so this _was_ fixed but apparently stopped working again recently

**Comment by ICooki3zI** [comment]
fixed
