### ISSUE TITLE
Seemingly no limit to shipment crates

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#105]
**Describe the bug**
Apparently there's no limit to how many shipment crates can be spawned. Either this or there's just a REALLY high limit. You can take off the conveyor belt as many crates as you can and they will never stop dropping down from the pipe. This can easily be abused to create lag on the server.

**To reproduce**
Steps to reproduce the behaviour:
1. Become industrial worker on CWU
2. Get to the packaging facility
3. Take a shipment box off the conveyor belt
4. Repeat step 3 infinitely

**Expected behaviour**
Shipment boxes are supposed to have a limit to how many can exist to prevent abuse.

**impulse version (press F1 in the bottom right):**
1.11.0

**Comment by sophfee** [comment]
@SpriteCran or @ICooki3zI can you look at this? I’m busy with Hammer integration.
