### ISSUE TITLE
splints bugged

### ISSUE THREAD

**Issue by Postmailer** [urnotnick/impulse-issues#107]
**Describe the bug**
splints dont even work anymore

**To reproduce**
Steps to reproduce the behaviour:
1. break your legs
2. try to use a splint
3. See error

**Expected behaviour**
for my legs to be fixed

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by ICooki3zI** [comment]
fixed
