### ISSUE TITLE
Purchased Apartments and Team Swapping Bug

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#108]
**Describe the bug**
When switching between 2 teams that allow you to carry over apartment ownership, such as Citizen and Civil Worker's Union, the door itself will remained owned and the keys will still work, but the panel beside the door will turn blue and indicate that the apartment is vacant, when it is, in fact, not.

**To reproduce**
Steps to reproduce the behaviour:
1. Start as Citizen
2. Buy an Apartment (I did 102 in Terminal Hotel)
3. Switch to CWU
4. Notice the bug

**Expected behaviour**
That the door's panel will indicate that the apartment is still owned, much like how it was previously.

**Screenshots**
![20221113184248_1](https://user-images.githubusercontent.com/106186291/201550954-e1c5f029-1cad-4276-8f0d-1d9dec38f2b2.jpg)

![20221113184251_1](https://user-images.githubusercontent.com/106186291/201550963-690cbb79-efbc-49cf-8649-fdf243c24731.jpg)

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
N/A

**Additional context**
https://medal.tv/games/garrys-mod/clips/Ip7EWVvfgt63q/d1337aLFiP58?invite=cr-MSxzWHYsMTIxNTM1MDQwLA

**Comment by Miraak11** [comment]
Alright so while I was gathering the screenshots and uploading the clip the door suddenly wasn't owned by me anymore, possibly a delayed removal of ownership

**Comment by Miraak11** [comment]
but it also won't let me purchase anymore apartments, it still thinks i own the apartment even though the panel says i dont and the door isn't owned by me anymore

**Comment by Miraak11** [comment]
https://medal.tv/games/garrys-mod/clips/IpcBo4Q0ImigE/d1337kb3an8m?invite=cr-MSxNaTcsMTIxNTM1MDQwLA

**Comment by ICooki3zI** [comment]
In the recent update 1.11.3 I fixed the issue not being able to purchase apartments after switching teams. However, it will still sell them when switching teams you'll just need to buy it back.
