### ISSUE TITLE
Descriptions Resetting on Server Restart

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#109]
**Describe the bug**
Descriptions Reset after Server Restart

**To reproduce**
Steps to reproduce the behaviour:
1. Wait for Server to restart
2. Launch GMOD
3. Join Server
4. Join a Team
5. Get asked to enter another description

**Expected behaviour**
If a description was made before, the prompt should not show up. (it also shows up if you die from the team and it reassigns you to Citizen) 

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by ThatBapGuy** [comment]
UPDATE: Now it is asking on joining, it used to not ask before when you joined the server and required you to fill it out when you died from whatever team you joined.
![image](https://user-images.githubusercontent.com/96233752/202055291-c6de7d83-ab80-4ef3-a679-27bd3351f653.png)

**Comment by ICooki3zI** [comment]
fixed
