### ISSUE TITLE
Scanners can drag people

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#11]
**Describe the bug**
Scanners can drag restrained people

**To reproduce**
Steps to reproduce the behaviour:
1. Be a scanner
2. Press E to drag a restrained citizen

**Expected behaviour**
Scanners should not be able to drag citizens as they are drones

**impulse version (press F1 in the bottom right):**
1.8.1

**Comment by urnotnick** [comment]
I believe this has been fixed.
