### ISSUE TITLE
Problem logging in after a while, cant do much.

### ISSUE THREAD

**Issue by NULL121** [urnotnick/impulse-issues#110]
**Describe the bug**
Cannot gain xp, type in chat, type in OOC, turn my flashlight on, submit a report in F3, withdraw or gain money, lost my entire stash too. And also everytime i log back in it makes me put my description back in. 

**To reproduce**
Steps to reproduce the behaviour:
1. Play the game a couple months ago.
2. Log in for the first time after a couple months.
4. Notice problem.

**Expected behaviour**
All of the above I guess.

**Screenshots**
![20221115004915_1](https://user-images.githubusercontent.com/118233068/201804491-86d8d56a-f684-448b-8393-1d6c0eac3618.jpg)

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
No Lua error.

**Additional context**
I think its an issue with maybe a server update, as I played a couple months ago (around april or may) but came back recently, and only am experiencing the issue on this server only. I even have all my stats saved, but cant do any of the things listed at the top.

**Comment by sophfee** [comment]
Investigating

**Comment by sophfee** [comment]
Patched, will be pushed tonight

**Comment by NULL121** [comment]
How do I re-open this?
