### ISSUE TITLE
Forcefield bypass

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#111]
**Describe the bug**
Most forcefields on the map can be bypassed very easily by pretty much anyone. You just have to squeeze yourself between the Forcefield Pillar entity and the energy field itself, the issue seems to stem from the Pillar having a bad hitbox that allows this to happen.

**To reproduce**
Steps to reproduce the behaviour:
1. Find an active forcefield
2. Find the side of the forcefield that shows a name popup "Forcefield Pillar" (there's always only one pillar that does this)
3. Squeeze yourself between the Pillar entity and the field by moving forward, wiggle a little bit
4. Successfully bypass the forcefield

**Expected behaviour**
Forcefields are supposed to prevent unauthorized entry, not be a cosmetic prop.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/47142477/202021090-1c7d6db4-54b0-44ae-9427-540f0a1f2af3.png)

**impulse version (press F1 in the bottom right):**
1.11.2

**Comment by ICooki3zI** [comment]
Fixed
