### ISSUE TITLE
OSR Scope Key is useless

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#112]
**Describe the bug**
The item "Scope Activation Key" for the OSR (Combine Sniper) has no use and is obviously broken. The rifle works perfectly fine without it and the scope can be used in first person no matter if you equip it or not. In third person there is no zoom feature at all, with both the scope key equipped and unequipped.

**To reproduce**
Steps to reproduce the behaviour:
1. Become RANGER EOW+
2. Realize that you can use the rifle scope without having the "Scope Activation Key" equipped
3. Be useless in third person due to no zoom at all, scope key equipped or unequipped

**Expected behaviour**
The scope key item is supposed to have a use and not be a 1kg paperweight.

**impulse version (press F1 in the bottom right):**
1.11.2

**Comment by Miraak11** [comment]
This isn't broken, originally the OSR was able to be aimed without looking down the scope, much like how a RANGER OWS can use the AR2 without the scope attached. This was changed so the scope is always active, I assume for balancing purposes, but the activation key item was never removed.

**Comment by ICooki3zI** [comment]
Removed from vendor
