### ISSUE TITLE
BSL SV Voicelines

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#116]
**Describe the bug**
For some Taglines, when a SV dies. The voice line plays the wrong tagline and number.

**To reproduce**
1. Join Server
2. Go CCA
3. Set self to OfC+
4. Die and listen to BSL radio message

**Expected behavior**
The BSL voice line to state the correct tagline and number.

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
If applicable, post the error here in full.

**Additional context**
If I am remembering correctly, it happens with the tagline Tap atleast.

**Comment by ThatBapGuy** [comment]
Such as Tap-3 = Hero-1

**Comment by Miraak11** [comment]
This is a duplicate report of #100 by me btw

**Comment by ThatBapGuy** [comment]
> This is a duplicate report of #100 by me btw

Fuck. Closing it then lmfao
