### ISSUE TITLE
.45 ACP Not Loading Properly Into M1911

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#117]
**Describe the bug**
When loading the appropriate ammo into the new weapon, the M1911, it allows you to load the ammunition but the bullets will not appear in the gun after doing so. Strangely enough, you can even refill the ammo you've loaded even though your ammo count will show no bullets in the gun. This is not merely a UI bug; you cannot shoot even with the ammo loaded.

**To reproduce**
Steps to reproduce the behaviour:
1. Get M1911 and ammo
2. Load ammo into weapon
3. Notice the error, try to unload ammo
4. Notice second part of bug, loading ammo the game claims you don't have

**Expected behaviour**
That the ammo will load into the weapon properly, like with the M3 Grease Gun.

**Screenshots**
https://medal.tv/games/garrys-mod/clips/L9m0lVwR0DMpP/d1337QPq6IlC?invite=cr-MSw2V2EsMTIxNTM1MDQwLA
**impulse version (press F1 in the bottom right):**
 1.11.3

**Lua error**
N/A

**Additional context**
It might be useful to know I loaded up an M3 Grease Gun before the M1911, and the Grease Gun worked fine but the M1911 has this issue. This also occured in a single life.

**Comment by sophfee** [comment]
M1911 uses pistol ammo
