### ISSUE TITLE
Mini-14 scope model inverted

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#118]
**Describe the bug**
The scope model on the Mini-14 in thirdperson is placed incorrectly, the wrong end of the scope is facing the shooter.

**To reproduce**
Steps to reproduce the behaviour:
1. Craft Mini14 and a hunting scope
2. Equip both things
3. Go into third person

**Expected behaviour**
The wider, longer end of the scope is supposed to face outward, and the smaller one towards the shooter.

**Screenshots**
![image](https://user-images.githubusercontent.com/47142477/206250999-ad415d5b-79d0-4d9f-8e62-10b2a12f5327.png)
![image](https://user-images.githubusercontent.com/47142477/206251087-6ccc557a-f3c0-4ec3-88d5-a60f6b2841cd.png)

**impulse version (press F1 in the bottom right):**
1.11.2

**Additional context**
Second image provided for reference, scope of same type installed on a M14.

**Comment by ICooki3zI** [comment]
Fixed
