### ISSUE TITLE
BSLs gone

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#119]
**Describe the bug**
BSLs don't seem to register at all. No ping, no death log in the HUD, nothing. Right now only tested on the CP team, perhaps there's the same problem with OTA

**To reproduce**
Steps to reproduce the behaviour:
1. Become CP
2. Die

**Expected behaviour**
There's meant to be a BSL on CP death

**impulse version (press F1 in the bottom right):**
1.11.3 (according to discord announcement, ingame 1.11.2)

**Comment by sophfee** [comment]
Tracked & Investigating
