### ISSUE TITLE
Able to keep callsign as an i1, after switching from OfC+

### ISSUE THREAD

**Issue by XtraFry** [urnotnick/impulse-issues#12]
**Describe the bug**
After setting your tagline on OfC+, you can switch to anything under Union i1 and the tagline sticks which obviously you wouldnt want to avoid confusion.

**To reproduce**
Steps to reproduce the behaviour:
1. Flag up as OfC.
2. Set Tagline
3. Switch to Union i1 or lower.
4. See tagline issue.

**Expected behaviour**
It just needs to be locked even when you switch teams.

**Screenshots**
(None)

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by urnotnick** [comment]
not necessarily a bug, just never prevented callsign being assigned on ranks lower than OfC
