### ISSUE TITLE
Instant CP respawn

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#120]
**Describe the bug**
There currently is no cooldown for respawning at the train station as CP after death and picking the CP team again.

**To reproduce**
Steps to reproduce the behaviour:
1. Die as CP
2. Immediately appear at the train station
3. Immediately be able to pick the same team

**Expected behaviour**
Cooldowns are supposed to be in place.

**impulse version (press F1 in the bottom right):**
1.11.3 (according to discord announcement, ingame 1.11.2)

**Comment by sophfee** [comment]
Closing, this is tied directly to #119
