### ISSUE TITLE
BSLs

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#121]
**Describe the bug**
When dying as a non supervisor rank, the BSL calls out for "Hero-0" at the body. (BSLs have no audio at all for non-SVs but show visually)

**To reproduce**
Steps to reproduce the behaviour:
1. Go on Civil Protection
2. Die

**Expected behaviour**
Either no tagline shows up during the BSL speech or the BSL says the actual unit's information.

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by Miraak11** [comment]
[ERROR] gamemodes/landis-hl2rp/plugins/dispatch/sh_biosignal.lua:107: attempt to index a nil value
  1. func - gamemodes/landis-hl2rp/plugins/dispatch/sh_biosignal.lua:107
   2. unknown - lua/includes/extensions/net.lua:33

**Comment by ICooki3zI** [comment]
Fixed
