### ISSUE TITLE
Prison end up jailing everyone into one cell

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#122]
**Describe the bug**
After a while, the jails begin to pile up with citizens being jailed in one cell.

**To reproduce**
Steps to reproduce the behaviour:
1. Wait after a few arrests occur (Prob 15 idk an actual number)
2. Get arrested alongside with other people
3. See them flood into one cell

**Expected behaviour**
To be evenly distributed between all cells

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.11.2 

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by sophfee** [comment]
This was never a thing.
