### ISSUE TITLE
Random Lua Error upon trying to access Offline Camera

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#123]
**Describe the bug**
Accidentally clicked a offline camera and got a lua error upon pressing view.

**To reproduce**
Steps to reproduce the behaviour:
1. Open Terminal
2. Click a camera that is Offline
3. Get error

**Expected behaviour**

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**

[ERROR] gamemodes/landis-hl2rp/plugins/scanner/cl_net.lua:34: Tried to use a NULL entity!
  1. GetPos - [C]:-1
   4. func - gamemodes/landis-hl2rp/plugins/scanner/cl_net.lua:34
    5. unknown - lua/includes/extensions/net.lua:33

**Additional context**

**Comment by ICooki3zI** [comment]
Yeah because they are offline
