### ISSUE TITLE
APF Bug(s)

### ISSUE THREAD

**Issue by johnnyroastbeef** [urnotnick/impulse-issues#126]
**Describe the bug**
A. APF when shooting, if hit with either the Mosin or the AK47 or any weapon that applies major knockback, the APF minigun resets and cannot spin up and we cannot fight these people. (https://youtu.be/fpu6xrHI4wE)

B. Certain APF VCs apply no sound or do not work.
**To reproduce**
A. Attempt to shoot while being shot by the AK-47 or the Mosin

B. Attempt to use vcs that overlap with default combine vcs and some that don't work due to incorrect or missing sounds.
**Expected behavior**
A. Be able to return fire while under fire

B. Hear the beautiful apf voice.
**Screenshots**

**impulse version (press F1 in the bottom right):** 1.11.2

**Lua error**
N/A

**Additional context**
PLEASE I LOVE YOUR CLASS I WANT TO USE IT TO THE FULL POTENTIAL

**Comment by Miraak11** [comment]
Pretty sure point A is an intended addition as a counter to APF

**Comment by elrobusto** [comment]
It's not just AK and Mosin that seems to do this, it's every weapon except maybe the weakest like the USP. Nobody ever mentioned that the AK would counter APF, I've heard something about Mosin being the intended counter but that's it.

**Comment by johnnyroastbeef** [comment]
Rumors of the MCX doing it too, but cannot confirm have not fought any

**Comment by sophfee** [comment]
this isn't entirely "intended" but it's known about for a reason, I can look into reducing knockback

**Comment by SpriteCran** [comment]
Could you elaborate on B?

**Comment by Astrroo** [comment]
done
