### ISSUE TITLE
Forcefield Glitch

### ISSUE THREAD

**Issue by PhantomTao** [urnotnick/impulse-issues#129]
**Describe the bug**
When crouching at the edge of a force field you are able to phase thru it even tho its on
**To reproduce**
Steps to reproduce the behaviour:
1. Go to a forcefield crouch at the corner of it walk forward

**Expected behaviour**
You arent able to pass the forcefield because it is on. 

**Screenshots**
https://medal.tv/games/garrys-mod/clips/Nrgg7FD7JSXRd/d1337MtxoU0E?invite=cr-MSxXWUcsMTYyNjc3MDYs

https://medal.tv/games/garrys-mod/clips/Nrg44-3ro9Uy8/d1337sKSzGf4?invite=cr-MSx4NXAsMTYyNjc3MDYs

**Comment by Miraak11** [comment]
this is already a known issue

**Comment by elrobusto** [comment]
This issue is no longer relevant
