### ISSUE TITLE
EOW+ Bug

### ISSUE THREAD

**Issue by buffingtonpp** [urnotnick/impulse-issues#13]
**Describe the bug**
As an Overwatch Unit, with a rank selected I have my in-character name.

**To reproduce**
Steps to reproduce the behaviour:
1. Switch to OTA.
2. Head to the rank officer and get rank EOW+
3. See your name is still your previous IC name.

**Expected behaviour**
Get your regular Overwatch name.

**Screenshots**
https://cdn.discordapp.com/attachments/920389544220704818/929918253768245288/20220110020240_1.jpg

**impulse version (press F1 in the bottom right):**

**Comment by buffingtonpp** [comment]
Adding onto this, does not let you access the f6 menu when flagged up as EOW+

**Comment by urnotnick** [comment]
patched
