### ISSUE TITLE
Minor Room Terminal Text Bug

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#131]
**Describe the bug**
When adding someone to a door, the prompt below the selected name will read "Grant Access" and switch to "Revoke Access" once that person is added. However, if you then select another person from the drop-down menu, the text will still read "Revoke Access", though clicking it will still grant that new person access as well.

**To reproduce**
Steps to reproduce the behaviour:
1. Purchase an Apartment with the Terminal
2. Add a random player via the Terminal interface
3. Notice the text change to "Revoke Access", then select a different person
4. Notice that it still reads "Revoke Access"

**Expected behaviour**
That the text will read "Grant Access" for every new person you wish to add to a door.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
N/A
**Additional context**
https://medal.tv/games/garrys-mod/clips/QeJorc1wWfBNU/d13373BHnoxQ?invite=cr-MSxSZmksMTIxNTM1MDQwLA

**Comment by sophfee** [comment]
This is ironed out heavily in 1.12 already, thanks for the report
