### ISSUE TITLE
Black model

### ISSUE THREAD

**Issue by CMDRKane** [urnotnick/impulse-issues#133]
When you join you may become a literally gmod ARG, like the model is completely black

**To reproduce**
Steps to reproduce the behaviour:
1. Join the server
2. Walk out of trainstation
3. Spawn a dupe
4. You become a shadow man
I should see a regular model
![image_2023-01-17_165701298](https://user-images.githubusercontent.com/122945908/213054620-9d1b5c8e-f541-451b-b5d2-2a24bb07fc64.png)

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by sophfee** [comment]
Can you list the following from the device you took the screenshot with
- CPU
- Memory
- GPU

**Comment by CMDRKane** [comment]
![image_2023-01-18_170644090](https://user-images.githubusercontent.com/122945908/213331675-efbf9698-9c9e-4281-9743-877ed746e490.png)
![image_2023-01-18_170659217](https://user-images.githubusercontent.com/122945908/213331722-32998c5c-b24c-41b3-9d06-9a45b5420ee0.png)
![image_2023-01-18_170922709](https://user-images.githubusercontent.com/122945908/213331997-ecd31f6c-42e0-4637-8356-628ecda39f83.png)

**Comment by Astrroo** [comment]
Dupe may contain an E2 that modifies playermodel color. Not an issue on our end.
