### ISSUE TITLE
medkit bug 

### ISSUE THREAD

**Issue by combinead** [urnotnick/impulse-issues#136]
**Describe the bug**
i was healing someone and he needed another heal in a row and it would not heal him i used all 4 medkits and he did not get a single hp gain

**To reproduce**
1. find someone at extremely low health (13 was what he was on) 
2. use med-kit
3. heal him again and see if it fails
4. if it fails the bug is reproducing (it might not always reproduce it)

**Screenshots**
medal clip https://medal.tv/games/garrys-mod/clips/RIz1to5HAR7FM/d133779S0ve8?invite=cr-MSxXa3ksMTU5NDQwMjg0LA

**impulse version (press F1 in the bottom right):** 1.11.2

**Lua error**
If applicable, post the error here in full.

**Additional context** if you need me dm me on discord Combine Advisor#7646

**Comment by Miraak11** [comment]
Some extra context, he was healing me as a CMU when I was at 13 HP. One medkit brought me up to 70 HP, but when he tried healing me again, it consumed his medkit but did not heal me at all. I was on around 28-29 hunger at a time, in case that's relevant somehow. He used about 3 medkits on me after the initial one that healed me but none worked.

**Comment by sophfee** [comment]
Looking into this, thank you for the report!

**Comment by combinead** [comment]
oddly enough if you heal a different faction player for me at least it healed the guy but wouldn't heal civi or vort

**Comment by SpriteCran** [comment]
Issue has been fixed!

**Comment by combinead** [comment]
awesome!
