### ISSUE TITLE
Cannot Join Server Due to Character Descriptions

### ISSUE THREAD

**Issue by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [urnotnick/impulse-issues#139]
**Describe the bug**
I haven't been able to join the hl2rp server at all in the year 2023 and sparsely at all in 2022, if at all. This is because of an issue I've been having with the character descriptions feature. Each time I attempt to join, I am allowed onto the main menu, but as soon as I hit "Play" a popup box displays telling me to enter a character description since I wasn't online at the time of the addition of this feature. That's fine, and I'd gladly enter a description and continue on, but when I hit "enter" after typing in a description, I am booted out of the server and given an error code that doesn't make any sense to me. There will be a screenshot of it provided below

I absolutely adore this server, but I have had to look to alternatives like Vanilla and Cataclysm since then because of this. A timely response would be appreciated, no pressure though. Since I understand this may be a complicated bug to fix

**Screenshots**
![20230129130444_1](https://user-images.githubusercontent.com/102838245/215347352-2776c4a2-2ab7-41ee-9276-37b65cb0d7c2.jpg)

**impulse version (press F1 in the bottom right):**
_1.11.2_

**Comment by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
PS: Steam username is ADAM

**Comment by sophfee** [comment]
Remove punctuation from your description. This is not a bug. "Bad Characters" means a letter in your description is registered as improper by the server. Remove `'"` from your description as well, these are the most common culprits
