### ISSUE TITLE
OFC can promote to I2+

### ISSUE THREAD

**Issue by Cairothefox** [urnotnick/impulse-issues#141]
**Describe the bug**
When a OFC you go to F6 and click prmt Channel in the PDA and you can promote units to i2+ Found out by mistake accidental promotion. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to F6
2. Click on PRMT
3. Scroll down to Unit number and click promote as OFC
4. Unit from i3 can be promoted to i2+

**Expected behaviour**
OFC should not be able to Promote to I2 unless SQL and the F6 should deny it as such if wishing to promote to I2 as OFC

**Screenshots**

**impulse version (press F1 in the bottom right):** 1.11.2

**Lua error**
If applicable, post the error here in full.

**Additional context**
Ofc should not be able to promote to i2+ as the current rank the Ofc is. Should be at least SQl+ locked for the rank to be given as a whitelist

**Comment by SpriteCran** [comment]
This has never been an issue nor changed; OfC has had the ability to promote i3s. I'll talk with Alpha whether or not he wants this to be the case.
