### ISSUE TITLE
the confiscation menu breaks if you press e too much

### ISSUE THREAD

**Issue by REALSLIMSHADY101010101** [urnotnick/impulse-issues#142]
**Describe the bug**
if you go to confiscate etc a ruined biolink, if you press e too many times you get softlocked into the confiscation menu because of it appearing several times. only another unit can help you to get out of this by confiscating it themselves.

**To reproduce**
Steps to reproduce the behaviour:
1. go to contraband item
2. spam e on it
3. get stuck in the menu
4. cry

**Expected behaviour**
the menu only showing up once

**Screenshots**
did nor take

**impulse version (press F1 in the bottom right):**
1.11.2

**Lua error**
no lua error

**Additional context**
i shittered

**Comment by Astrroo** [comment]
This happens with pretty much every VGUI element. Solution? Don't spam E.
