### ISSUE TITLE
Ration Distribution Machine says Online when its offline

### ISSUE THREAD

**Issue by buffingtonpp** [urnotnick/impulse-issues#144]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Go to RDC
2. Look at it during ration downtime
3. See problem

**Expected behaviour**
It says offline 

**Screenshots**
If applicable, add screenshots to help explain your problem.](https://imgur.com/a/ATitAZp)

**impulse version (press F1 in the bottom right):**
1.12

**Lua error**
If applicable, post the error here in full.

**Additional context**
It was right after server opening

**Comment by buffingtonpp** [comment]
Okay its only after server restart after it cycles to online and then offline its fine

**Comment by Astrroo** [comment]
Duplicate issue.
