### ISSUE TITLE
1.12.0 - F1/Main menu

### ISSUE THREAD

**Issue by zachun** [urnotnick/impulse-issues#147]
**Describe the bug**
Clicking on the button "DONATE" sends you to the options tab

**To reproduce**

1. Get on server
2. Click F1
3. Click donate
4. Sends you to "OPTIONS"

**Expected behaviour**
A pop-up with the panel link towards the donation page to appear to the player

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.12.0

**Lua error**
N/A

**Additional context**
N/A

**Comment by justinbrick** [comment]
This was resolved in the latest hotfix. Thanks for reporting!
