### ISSUE TITLE
1.12.0 - cl_craftingmenu

### ISSUE THREAD

**Issue by zachun** [urnotnick/impulse-issues#149]
**Describe the bug**
[ERROR] gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua:87: attempt to index global 'quit' (a nil value)
  1. unknown - gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua:87

Timer Failed! [Simple][@gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua (line 86)]

**To reproduce**

1. Spawn workbench
2. Click E on it
3. See error

**Expected behaviour**
No error.

**impulse version (press F1 in the bottom right):**
1.12.0

**Lua error**
[ERROR] gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua:87: attempt to index global 'quit' (a nil value)
  1. unknown - gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua:87

Timer Failed! [Simple][@gamemodes/impulse/gamemode/core/vgui/cl_craftingmenu.lua (line 86)]

**Additional context**
I cannot craft anything due to this glitch, it says that the other mixtures are locked and not for my level despite the fact that I'm lvl 10 crafting

**Comment by zachun** [comment]
Update - Now it does let me craft but it appears under the 'Locked mixtures'

**Comment by zachun** [comment]
Chat is also overlapping the crafting menu making some recepies unreadable
![image](https://user-images.githubusercontent.com/72348423/219894851-42e77892-d2f8-4172-9d1a-937f25eaf4b3.png)

**Comment by DeerDust** [comment]
Also, the Hardhat, Fedora, and Black jacket are errors for me during this issue 
![image](https://user-images.githubusercontent.com/125767464/219896562-1e5a258a-4b76-4e67-823a-e4444ae342cf.png)

**Comment by DeerDust** [comment]
lol what the fuck why did it show my desktop 
I hope yall like a ranger sitting in Caesar's chair
