### ISSUE TITLE
Selling doors issue

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#15]
**Describe the bug**
Moderators cannot fully sell doors via the command; it just sells the door, but the property can't be bought.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to a door
2. Force sell it
3. Attempt to buy

**Expected behaviour**
Once a moderator sells the door, it should be available for people to buy it.

**Screenshots**
If you really need, I will post some

**impulse version (press F1 in the bottom right):**
1.8.1

**Lua error**
N/A

**Additional context**
N/A

**Comment by urnotnick** [comment]
mod tools were never reworked for the new property system, expect a /forcesellproperty command in next update (tho it wont be needed most likely)
