### ISSUE TITLE
Camera Viewing

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#150]
**Describe the bug**
Viewing Cameras in the Terminal produce a LUA error constantly.

**To reproduce**
Steps to reproduce the behaviour:
1. Open Terminal
2. View Camera

**Expected behaviour**
No LUA error

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
[ERROR] lua/postprocess/color_modify.lua:23: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. DrawColorModify - lua/postprocess/color_modify.lua:23
    3. DrawCombineCameraOverlay - gamemodes/landis-hl2rp/plugins/combineoverlay/cl_overlay.lua:655
     4. v - gamemodes/landis-hl2rp/plugins/combineoverlay/cl_overlay.lua:1083
      5. unknown - lua/includes/modules/hook.lua:96 (x170)

**Additional context**

**Comment by justinbrick** [comment]
addressed in latest hotfix
