### ISSUE TITLE
OTA cant flag to citizen unless in train station

### ISSUE THREAD

**Issue by w0kman** [urnotnick/impulse-issues#156]
**Describe the bug**
Cannot swap off ota without going to train station

**To reproduce**
Steps to reproduce the behaviour:
1. Be an ota unit
2. Attempt to switch to citizen role
3. Notice you cannot 
4. Go to train station, and you can

**Expected behaviour**
Able to switch to citizen

**Comment by justinbrick** [comment]
This was fixed shortly after, all that's left is cleaning up some of the code so people can't become citizens in Nexus. Thanks for reporting!
