### ISSUE TITLE
Player card missing in report menu

### ISSUE THREAD

**Issue by w0kman** [urnotnick/impulse-issues#157]
**Describe the bug**
Clicking player card in the report menu shows nothing

**To reproduce**
Steps to reproduce the behaviour:
1. Go to report
2. Click player card
3. See error

**Expected behaviour**
See player card

**Comment by justinbrick** [comment]
I'm unable to replicate. Is this regarding when there is an invalid player?

**Comment by w0kman** [comment]
> I'm unable to replicate. Is this regarding when there is an invalid player?

when claiming a report, there is a button to open the players player card, which gives us access to tools and such. this doesnt show for me

**Comment by justinbrick** [comment]
Issue resolved, thanks for reporting
