### ISSUE TITLE
dismantling cans giving possibly way too much more metal than usual

### ISSUE THREAD

**Issue by aidanatorr** [urnotnick/impulse-issues#16]
**Describe the bug**
i bought a few cans to increase my scrapping level, and noticed that it gave me way more metal than usual. I bought 6 cans i got nearly 20 metal plates from them, I am not the only person experiencing this issue.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to a vending machine
2. Buy a drink
3. Dismantle it
4. Get lots of metal plates

**Expected behaviour**
I'd expect metal to be given out from dismantling cans, but I dont think giving out this much was intended 

**Screenshots**
This is a screenshot i took of my inventory after scrapping 6 cans with 13 metal plates in my inventory https://cdn.discordapp.com/attachments/807412569714982912/930327712365703168/20220111000556_1.jpg

**impulse version 1.9.0:**

**Lua error**
N/A

**Additional context**
N/A

**Comment by urnotnick** [comment]
Fixed
