### ISSUE TITLE
Donate button takes to settings menu

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#161]
**Describe the bug**
Click the Donate button and it opens the settings menu

**To reproduce**
Steps to reproduce the behaviour:
1. Press F1
2. Click Donate
3. See Results

**Expected behaviour**
To be taken to the donation page.

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment]
Resolved, thanks for reporting!
