### ISSUE TITLE
Bug with CP xray involving the medkit

### ISSUE THREAD

**Issue by RebelJoshua** [urnotnick/impulse-issues#166]
**Describe the bug**
when i choose the medkit on xray cp it just bugs on my screen

**To reproduce**
Steps to reproduce the behaviour:
1. Go CP xray
2. Choose the medkit

**Expected behaviour**
No bugs medkit be on hands not on face

**Screenshots**
![image](https://user-images.githubusercontent.com/125770151/219900962-d03300f3-ba28-41df-8f6a-e6a815f6a44b.png)

**Lua error**
The addon "plutonic" Is creating errors, check the Problems menu for details

**Comment by justinbrick** [comment]
fixed in latest patch, thanks for reporting!
