### ISSUE TITLE
Apartments next to GGs have broken terminals.

### ISSUE THREAD

**Issue by sospeti** [urnotnick/impulse-issues#169]
Terminals show "label" three times and you cannot buy the appartments.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the apartments next to GGs.
2. Click on the terminal.
3. You will see label repeated 3 times.
4. Trying to buy the apartment does not work.

**Expected behaviour**
You should be able to buy the apartment.

**Screenshots**
[https://cdn.discordapp.com/attachments/907380171189923941/1076630898700734564/image.png](url)

**impulse version (press F1 in the bottom right):**
1.12.0
**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment]
These were improperly set up. Oops! I had fixed them yesterday. Thanks for reporting!
