### ISSUE TITLE
Health station not stopping bleeding when used

### ISSUE THREAD

**Issue by GormDaGamer** [urnotnick/impulse-issues#17]
**Describe the bug**
Bio gel injection not stopping bleeding.

**To reproduce**
Steps to reproduce the behaviour:
1. get bleeding effect.
2. go to bio gel.
3. then still bleed.

**Expected behaviour**
that the bleeding would stop.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
N/A

**Additional context**
Health vial also do not stop bleeding, but idk if its supposed to stop bleeding.
Swift told me bio gel should stop bleeding.

**Comment by urnotnick** [comment]
*should* be fixed now
