### ISSUE TITLE
bug with the playermodel changer

### ISSUE THREAD

**Issue by RebelJoshua** [urnotnick/impulse-issues#170]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'DC
2. Click on the woman that changes PMs

**Expected behaviour**
no error + all PMs be good and none saying "ERROR"

**Screenshots**
![image](https://user-images.githubusercontent.com/125770151/219903644-f8ffc339-c60d-4a48-8a8c-63f5e5f3a9c4.png)

**Lua error**
![image](https://user-images.githubusercontent.com/125770151/219903652-d3412faa-3229-4dd1-ae1a-4a0a1c3f94c5.png)

**Comment by justinbrick** [comment]
This was fixed earlier yesterday - content error should be fixed as well. Thanks for reporting!
