### ISSUE TITLE
Unable to Promote/Demote any units

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#171]
**Describe the bug**
No PDA location exists to demote or promote units.

**To reproduce**
Steps to reproduce the behaviour:
1. Look at PDA
2. See missing area

**Expected behaviour**
able to promote

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment]
This should be fixed now, done in the Dossier section of PDA. Thanks for reporting!
