### ISSUE TITLE
Crafting shows Level 1 options as only being unlocked when you're level 10 but can craft everything

### ISSUE THREAD

**Issue by buffingtonpp** [urnotnick/impulse-issues#172]
**Describe the bug**
While at a general workbench the crafting menu displays level 1 crafting recipes as unlocked only while I'm level 10, but I am still able to craft all level of tiems

**To reproduce**
Steps to reproduce the behaviour:
1. Go to General Workbench
2. Click E
3. See issue

**Expected behaviour**
Unlocks would be displayed with the proper level

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://imgur.com/a/QuJQWhF)

**impulse version (press F1 in the bottom right):**
1.12
**Lua error**
None

**Additional context**

**Comment by justinbrick** [comment]
Fixed yesterday, thanks for reporting!
