### ISSUE TITLE
Requesting Medical provides LUA Error

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#174]
**Describe the bug**
Calling for Medical provides a LUA error.

**To reproduce**
Steps to reproduce the behaviour:
1. Click on Request Medical
2. See error

**Expected behaviour**
I would imagine a SFX and no lua error.

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
[ERROR] gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pdacommand.lua:18: attempt to call global 'pdaSound' (a nil value)
  1. DoClick - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pdacommand.lua:18
   2. unknown - lua/vgui/dlabel.lua:237

**Additional context**

**Comment by justinbrick** [comment]
Fixed in latest patch
