### ISSUE TITLE
Overwatch BSLs report as CCA Divisions to CCA

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#176]
**Describe the bug**
When a Overwatch unit dies, CCA hears their BSL as a Division name.

**To reproduce**
Steps to reproduce the behaviour:
1. Go onto CCA
2. Have OTA die
3. Hear the issue

**Expected behaviour**
Overwatch taglines potentially

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by Miraak11** [comment]
this has been a thing for a long time btw, through c8 and c24 at least. tbh i dont mind it. there's no voicelines for ota taglines anyway, unless we AI generate some

**Comment by Astrroo** [comment]
This is intentional behavior as OTA do not have Dispatch voicelines to boot.

**Comment by Astrroo** [comment]
Refer to the comment above.
