### ISSUE TITLE
(1.12) 7.62 ammo box error

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#178]
**Describe the bug**
7.62 ammo becomes an error upon being dropped in any circumstance, be it from a player's inventory or from dead OTA. In its error state it cannot be picked back up.

**To reproduce**
Steps to reproduce the behaviour:
1. Obtain 7.62 ammo by crafting or kill an OTA
2. Drop 7.62 ammo if you obtained it by crafting
3. Observe that it is an error and cannot be picked back up

**Expected behaviour**
7.62 ammo is supposed to be visible and pickable from the ground

**impulse version (press F1 in the bottom right):**
1.12

**Comment by elrobusto** [comment]
Fixed

**Comment by elrobusto** [comment]
Issue reoccured on server, 7.62 box is an error again

**Comment by justinbrick** [comment]
I attempted a patch. Worked on dev server, not prod. Likely content error?

**Comment by justinbrick** [comment]
Error resolved. Thanks for reporting!
