### ISSUE TITLE
Bleeding bug

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#18]
**Describe the bug**
You can bleed from being hit with... stunstick. How? I don't know.

**To reproduce**
Steps to reproduce the behaviour:
1. Go CP
2. Hit someone with baton
3. Keep hitting until they start to bleed

**Expected behaviour**
Stunstick shouldn't cause bleeding.

**Screenshots**
N/A ATM

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
No lua error

**Additional context**
How does a baton make you bleed, it can only leave some ugly marks and that's all

**Comment by urnotnick** [comment]
Not a bug, bleeding is triggered by any source of player damage.
