### ISSUE TITLE
(1.12) Plutonic sound error

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#180]
**Describe the bug**
Was moving to sewers from Shell Beach, heard a gunfight happening, supposedly somewhere in the city then an error popped up for Plutonic. See lua error section.

**To reproduce**
Steps to reproduce the behaviour:
1. Be close to or be in a firefight
2. Have a chance to experience the error

**Expected behaviour**
Plutonic not supposed to give script errors

**impulse version (press F1 in the bottom right):**
1.12

**Lua error**

[plutonic] addons/plutonic/lua/weapons/plutonic_base/client/sound.lua:90: Tried to use a NULL entity!
  1. EmitSound - [C]:-1
   2. func - addons/plutonic/lua/weapons/plutonic_base/client/sound.lua:90
    3. unknown - lua/includes/extensions/net.lua:33

**Comment by elrobusto** [comment]
Fixed

**Comment by elrobusto** [comment]
Nevermind, just happened on the server again. I believe someone shot an M14 from afar and it appeared in the console.

**Comment by Astrroo** [comment]
provide more information, otherwise it'll be closed.

**Comment by justinbrick** [comment]
Going to mark this as complete, as we pushed a new version of Plutonic lately (fairly certain this is the fix) If it happens again, please re-open.
