### ISSUE TITLE
(1.12) Leather Jacket item has the model of Red Jacket

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#184]
**Describe the bug**
What it says in the title. In the crafting menu it looks like a black jacket, but if you wear it it gives you the exact model of the Red Jacket, a previous item on the list.

**To reproduce**
Steps to reproduce the behaviour:
1. Procure a tailoring bench
2. Make an item called Leather Jacket
3. Equip it and go into third person

**Expected behaviour**
Leather Jacket is supposed to be black (and badass)

**Screenshots**
What the item looks like in inventory:
![image](https://user-images.githubusercontent.com/47142477/219947193-9ee83c31-922d-4dcb-87d7-501001de3625.png)
What it looks like when worn:
![image](https://user-images.githubusercontent.com/47142477/219947215-1b47c795-ef0a-46fb-84c3-70ac32dcadfb.png)

**impulse version (press F1 in the bottom right):**
1.12

**Comment by Astrroo** [comment]
Make sure you do not have conflicting addons. This issue is common with conflictions. I'll check on our end.

**Comment by elrobusto** [comment]
@Astrroo it is not a bug on my end only, three other users have reported it
