### ISSUE TITLE
(1.12) Lockpicking skill no longer gives boost to unlocking

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#187]
**Describe the bug**
Before 1.12 the higher your Lockpicking skill level was, the shorter was the unlock time for doors. Now it seems to have defaulted to lvl 1 speed even at lvl 10.

**To reproduce**
Steps to reproduce the behaviour:
1. Get lockpicking lvl 10
2. Attempt lockpicking a door
3. Notice it no longer reduces the unlock time

**Expected behaviour**
Higher Lockpicking is meant to make unlocking faster

**impulse version (press F1 in the bottom right):**
1.12

**Comment by Astrroo** [comment]
not an issue
