### ISSUE TITLE
(1.12) Can no longer see player injuries

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#188]
**Describe the bug**
The feature of being able to see other players' injuries and if they're bleeding or not no longer works.

**To reproduce**
Steps to reproduce the behaviour:
1. Look at a wounded player
2. Notice you can't tell they're wounded

**Expected behaviour**
You're supposed to tell when a player is wounded or bleeding

**impulse version (press F1 in the bottom right):**
1.12

**Comment by Astrroo** [comment]
Not a bug, however, a likely oversight.
