### ISSUE TITLE
OSR scope

### ISSUE THREAD

**Issue by goatybebe** [urnotnick/impulse-issues#189]
**Describe the bug**
When holding RMB click to scope, whilst the OSR is equipped, the scope does not fully function and is incredibly slow as well as barely zooming in at all, the OSR should not be zooming in at 1.5x

**To reproduce**
Steps to reproduce the behaviour:
1. Equip OSR
2. Hold RMB whilst in first person
3. Scope in, using the OSR

**Expected behaviour**
Scope is meant to work to its full ability, as in scoping in as far as ~8x scope

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by elrobusto** [comment]
There is no zoom at all, not even 1.5x. Same behavior with the Hunting Scope on the M14.
