### ISSUE TITLE
Water can bug

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#19]
**Describe the bug**
Using water can in recipes does not give you the empty can back

**To reproduce**
Steps to reproduce the behaviour:
1. Buy a cooking stove/general workbench
2. Craft something that requires Water
3. See error

**Expected behaviour**
It should give you the empty can back

**Screenshots**
Not applicable

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
No

**Additional context**
No

**Comment by urnotnick** [comment]
This requires a framework mixture rework of the output system, supporting additional outputs. Not really a bug.

**Comment by urnotnick** [comment]
not a bug
