### ISSUE TITLE
(1.12) Infinite moonshine

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#191]
**Describe the bug**
Moonshine never runs out if used, you can drink it indefinitely. Also the usage function has no progress bar and if you spam it enough it "undrunks" you, removing all negative effects for movement.

**To reproduce**
Steps to reproduce the behaviour:
1. Get moonshine
2. Use it in inventory
3. Realize you can use it as many times as you want
4. Use it about 10 times in a row to get "undrunk"

**Expected behaviour**
The alcohol in the moonshine bottle is supposed to be finite.

**impulse version (press F1 in the bottom right):**
1.12

**Comment by justinbrick** [comment]
Issue has been resolved in the latest hotfix, and will take effect on next server update. Thanks for reporting!
