### ISSUE TITLE
LED Screens cannot be updated

### ISSUE THREAD

**Issue by oddnight** [urnotnick/impulse-issues#193]
**Describe the bug**
It's not possible to update the screen. So you have to delete the old screen and replace it with a new one if you want to change the text or a setting

**To reproduce**
Steps to reproduce the behaviour:
1. Get the LED screen tool
2. Set some settings and text on it
3. Place down the screen
4. Change any setting in the tool again
5. Try to update the screen
6. See the error

**Expected behaviour**
The screen gets updated with your new settings

**impulse version (press F1 in the bottom right):**
1.12

**Comment by zachun** [comment]
Read the options on the top left of your screen, it says you have to rightclick and not left-click, it works perfectly fine for me. If this is a real issue then this is the wrong place to report it as the LED screen addon is not from the HL2RP schema
