### ISSUE TITLE
1.12.0 - M14 Missing physics

### ISSUE THREAD

**Issue by zachun** [urnotnick/impulse-issues#195]
![20230219172944_1](https://user-images.githubusercontent.com/72348423/219958099-6eb781e7-b32f-4739-b49f-3f98dfbe4b7e.jpg)

**CONTEXT:**
I have dropped an M14 in and realizied it does not have physics making it impossible for me to pick up, Matters (Game Moderator) can vouch for this.

Server side collection pack maybe missing the new M14 model?

**Comment by elrobusto** [comment]
This is now fixed, M14 model got reverted to original
