### ISSUE TITLE
BSL'S don't count on death toll in F6

### ISSUE THREAD

**Issue by Cairothefox** [urnotnick/impulse-issues#196]
**Describe the bug**
when a CP's death has happened there BSL does not count towards the death toll on the F6 as it should even for overwatch 

**To reproduce**
Steps to reproduce the behaviour:
1. CP Dies
2. Check F6
3. Look at death counter in the F6

**Expected behaviour**
When a CP dies within the city limit or Overwatch trans human arm asset, the death counter should go up by 1 and have a 10 cycle timer before it expires so CP's are not asking for JW reason count.

**Screenshots**

**impulse version (press F1 in the bottom right):** 1.12.0

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment]
This has been put in a hotfix - while checked for syntax errors, it was not checked for logic errors, so it might not be resolved. I'll leave this open for the time being, but we might be able to consider it resolved, check back in tomorrow.

**Comment by justinbrick** [comment]
Good to go, thanks for reporting!
