### ISSUE TITLE
Vortigaunt sweep animation

### ISSUE THREAD

**Issue by ZPEFM** [urnotnick/impulse-issues#198]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Go on Vortigaunt
2. Use the broom
3. See animation's broken again

**Expected behaviour**
Broom animation should be fixed

**impulse version (press F1 in the bottom right):** 1.12.0

**Lua error**
If applicable, post the error here in full.

**Additional context**
Wasn't it fixed before?

**Comment by Astrroo** [comment]
Fixed with 1.12.1
