### ISSUE TITLE
Property system problem

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#2]
**Describe the bug**
When you get added to the door, you can't access the storage for some reasons (same for apartments).

**To reproduce**
Steps to reproduce the behaviour:
1. Get added to apartment
2. Attempt to open storage box
3. See error

**Expected behaviour**
Clearly, you should be able to open it.

**Screenshots**
Later.

**impulse version (press F1 in the bottom right):**
1.8.1

**Lua error**
No

**Additional context**
None

**Comment by urnotnick** [comment]
Patched in 1.9.0
