### ISSUE TITLE
[BUG] Defender Purchasables are unable to be purchased. 

### ISSUE THREAD

**Issue by SirBassilisk** [urnotnick/impulse-issues#20]
**Describe the bug**
All DEFENDER (Previously GRID) equipment not purchasable

**To reproduce**
Steps to reproduce the behaviour:
1. Be a DEFENDER (Rank does not matter)
2. Go to CP Requisition Supply Officer
3. Attempt to Purchase Camera repair kit
4. Purchase is locked (Greyed out)

**Expected behaviour**
The ability to purchase camera equipment as a DEFENDER.

**Screenshots**
https://cdn.discordapp.com/attachments/600767231487377432/930483711055638658/20220111101529_1.jpg

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
If applicable, post the error here in full.

**Additional context**
This issue persisted on each rank of CP that I have going from I1 to I4. None of them were able to purchase the camera repair kit inspite of it saying on the kit that it is for the DEFENDER Units. 
It is unknown if the Vicerator is also bugged in this way as the city code did not allow purchasing of one anyways.

**Comment by Astrroo** [comment]
Not an issue anymore.
