### ISSUE TITLE
Able to deplete Vending Machine stock without spending money

### ISSUE THREAD

**Issue by ThatBapGuy** [urnotnick/impulse-issues#202]
**Describe the bug**
Going up to a vending machine and pressing the buttons with 0 credits, depletes the stock of the vending machine.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Vending Machine
2. Make sure you have 0 credits on yourself
3. Press E on a option enough times to run it out of stock
4. See it runs out without having spent any credits or receiving any of the water

**Expected behaviour**
It to not deplete the water stock.

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by elrobusto** [comment]
Unable to replicate on the server, what vending machine did you use exactly? Just found the bug very interesting and went to check, couldn't deplete anything after many tries.

**Comment by justinbrick** [comment]
I'm unable to replicate. If this does happen again, please let us know. Thanks!
