### ISSUE TITLE
I Cant use the tool gun even though I have 3100Xp and have played on the server before and been able to use it.

### ISSUE THREAD

**Issue by MuteExe** [urnotnick/impulse-issues#203]
**Describe the bug**
I cant use the tool gun I also cant swap teams (even if I'm in spawn) I have no clue why this has started happening but I do have an Idea. The last time I played was on the 28th of dec 2022 and I just logged in today and this bug has started happening I've Uninstalled/ re-installed the game same with the addons, all my half-life games (all of them) and I've tried restarting my PC. Nothing! So I cant fix it so i can only assume its something to do with the 2023 update, I'll keep trouble shooting but until then, this is all I can do.

This is what appears in command line whenever I use it:

[impulse] [Notification] Toolgun restricted! Superadmin only!

**Comment by justinbrick** [comment]
Sorry for delay - is this still happening?

**Comment by MuteExe** [comment]
I’m on holiday right now but when I’m back home I’ll check.
