### ISSUE TITLE
[BUG] Defender unable to spawn Scanner

### ISSUE THREAD

**Issue by SirBassilisk** [urnotnick/impulse-issues#21]
**Describe the bug**
The DEFENDER's, regardless of rank from I1 to I4, are unable to use the City Scanners or spawn one in. 

**To reproduce**
Steps to reproduce the behaviour:
1. Be a DEFENDER
2. Enter into a Combine Terminal
3. Under Bulletin look for the Spawn Scanner button (Not actual name, I know)
4. Button is completely missing

**Expected behaviour**
When playing as DEFENDER the button to spawn or play as a city scanner is available in the Bulletin section of the Combine Terminal

**Screenshots**
https://cdn.discordapp.com/attachments/600767231487377432/930483710753652797/20220111101407_1.jpg

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
If applicable, post the error here in full.

**Additional context**
Issue is present regardless of rank (Tested for I1 to I4) and non work.

**Comment by urnotnick** [comment]
To my knowledge, this issue doesn't exist anymore and has been patched.
