### ISSUE TITLE
cant equip shirts or pants 

### ISSUE THREAD

**Issue by Sert-Studio** [urnotnick/impulse-issues#212]
**Describe the bug**

cant equip shirts or pants items 
 
**To reproduce**
Steps to reproduce the behaviour:
1. Go to a locker
2. get a shirt or pants item
3. try to equip
4. fail to equip

**Expected behaviour**

item will show as equipped and will show you wearing the item

**Additional context**

is bugged for both CWU and Civi

**Comment by Astrroo** [comment]
We're aware.
