### ISSUE TITLE
Tier two armor set bugged

### ISSUE THREAD

**Issue by NoOne252** [urnotnick/impulse-issues#213]
**Describe the bug**
Bug is pretty much not allowing a person to wear the Tier two armor set and it's giving off a Lua error when doing so this shouldn't be the case.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Tier two Armor item
2. Click on item in question after change into rebel suit.
3.  It should be giving an error or some cases not allowing it function properly.

**Expected behaviour**
Wear the Tier two armor set after changing into rebel clothes

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2941018134

**impulse version (press F1 in the bottom right):**

**Lua error**
[ERROR] gamemodes/landis-hl2rp/schema/scripts/sh_functions.lua:4: attempt to call method 'IsAlive' (a nil value)
  1. IsRebel - gamemodes/landis-hl2rp/schema/scripts/sh_functions.lua:4
   2. CanEquip - gamemodes/landis-hl2rp/schema/items/cosmetics/sh_cos_tiertwo_vest.lua:26
    3. unknown - gamemodes/impulse/gamemode/core/vgui/cl_inventoryitem.lua:271 (x2)

**Additional context**

**Comment by Astrroo** [comment]
All clothing is currently bugged and will receive a fix very soon.
