### ISSUE TITLE
APF Suit Charger Bug

### ISSUE THREAD

**Issue by johnnyroastbeef** [urnotnick/impulse-issues#214]
Describe the bug
Suit Charger sets SPS for APF to the wrong amount

To reproduce
1. Play APF
2. Interact with a suit charger

When interacting as APF with the suit charger, the user only gets 120 SPS instead of 150.

Expected behavior: Sets to 150.

Screenshots
N/A

impulse version (press F1 in the bottom right): most recent

**Comment by justinbrick** [comment]
I'm unable to replicate this. Would you be able to send in a video example?

**Comment by johnnyroastbeef** [comment]
Appears to have been resolved by another Developer

**Comment by justinbrick** [comment]
Alright, thanks for reporting!
