### ISSUE TITLE
Gray Shoes Bug

### ISSUE THREAD

**Issue by RebelJoshua** [urnotnick/impulse-issues#216]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the tailoring workbench
2 .Scroll down to Gray Shoes

**Expected behaviour**
See the shoes not the error

**Screenshots**
![image](https://user-images.githubusercontent.com/125770151/222917202-6eb4a496-9f27-4b46-b861-fbcd18c55b85.png)

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by justinbrick** [comment]
This was fixed in a hotfix a while back, thanks for reporting!
