### ISSUE TITLE
Factions bug

### ISSUE THREAD

**Issue by americaman17761** [urnotnick/impulse-issues#221]
**Describe the bug**
Ive recently returned to Landis HL2RP after my break in december, and ive noticed that when ever i try and switch to CA, or OTA it does not work. I have 1525 XP, and ive completed the OTA quiz so this makes no sense to me. Ive rejoined, reset, and even reinstalled GMOD and all addons except the landis ones.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to '...' F4
2. Click on '....' OTA or CA faction

**Expected behaviour**
It will not do anything, except close out the player menu screen.
**Screenshots**

**impulse version (press F1 in the bottom right):**
1.12.0

**Lua error**
If applicable, post the error here in full.

**Additional context**

https://user-images.githubusercontent.com/127168545/223308120-8935c894-881e-4290-96ff-6b95ae0a59a8.mp4

**Comment by jamminaf** [comment]
go to the nexus lobby
