### ISSUE TITLE
Grey Shoes Bug

### ISSUE THREAD

**Issue by Matters401** [urnotnick/impulse-issues#222]
**Describe the bug**
When the grey shoes are dropped onto the ground, an anomalous error is generated, which nobody can delete.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to inventory, 
2. Click on grey shoes.
3. Click drop

**Expected behaviour**
When a pair of grey shoes is removed from the inventory, a corresponding physical pair of shoes should be dropped onto the ground, which can be retrieved by anyone present.

**Screenshots**
https://i.imgur.com/mJXSXmk.jpeg

**impulse version (press F1 in the bottom right):**
1.12.0

**Lua error**
N/A

**Additional context**
not fair play

**Comment by elrobusto** [comment]
Duplicate issue

**Comment by justinbrick** [comment]
Duplicate #216
