### ISSUE TITLE
OTA Suit problem

### ISSUE THREAD

**Issue by Slothy32** [urnotnick/impulse-issues#23]
**Describe the bug**
OTA Do not get the suit as the changelogs says

**To reproduce**
Steps to reproduce the behaviour:
1. Get on OTA
2. Select a division 
3. See that you have 120 suit for all ranks and divisions (Excluding mace and nomad)
4. Echo still does get some new suit changes but they do not increase with rank

**Expected behaviour**
Rangers should have 70 suit while echos should have 120/140/180/240

**Screenshots**

**impulse version (press F1 in the bottom right):** 1.9.0

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by Astrroo** [comment]
Properly scales, no issue as of 8/20/22.
