### ISSUE TITLE
Gloves bugged on female PMs

### ISSUE THREAD

**Issue by CornOfTheFiles** [urnotnick/impulse-issues#24]
**Describe the bug**
Wearing gloves on female models doesn't work.

**To reproduce**
Steps to reproduce the behaviour:
1. Craft gloves
2. Wear gloves

**Expected behaviour**
You will have brown pants instead of gloves.

**Screenshots**
https://cdn.discordapp.com/attachments/800145497935052820/931190420816404540/unknown.png

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
-

**Additional context**
-

**Comment by ICooki3zI** [comment]
Works as intended.
