### ISSUE TITLE
Sound and Mic bug

### ISSUE THREAD

**Issue by JingJhon** [urnotnick/impulse-issues#250]
To put it plainly: There is a bug where people can't speak or hear a lot of the times. We've tried everything to fix it clientside from snd_restart to changing speaker config and it's just a server issue

To reproduce
1. its automatic, happens when people join or when they are just playing

**Expected behaviour**
The bug disables your ability to speak in game or hear

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
No clue what this means but it is on impulse
**Lua error**
N/A

**Additional context**
Usually happens to newer players

**Comment by sophfee** [comment]
report to facepunch/garrysmod-issues not here
