### ISSUE TITLE
Print code appearing when picking a rank as a combine team.

### ISSUE THREAD

**Issue by X-Mezo-X** [urnotnick/impulse-issues#26]
**Describe the bug**
When you pick a division and have the combine hud loading screen in your screen, for some odd reason a string of code displays while the loading screen plays.

**To reproduce**
Steps to reproduce the behaviour:
1. Become a combine team (CP or OTA)
2. Pick your division.
3. See Error.

**Expected behaviour**
The code that supposedly prints the text into the loading screen should not appear while the combine hud loading screen is playing.
**Screenshots**
https://cdn.discordapp.com/attachments/800145497935052820/931277245778128936/2022-01-13_22-00-44.mp4

1.9.0

**Lua error**
If applicable, post the error here in full.

**Additional context**
Nothing to note, just a funny bug.

**Comment by SpriteCran** [comment]
this is not a bug, this is a feature

**Comment by X-Mezo-X** [comment]
> this is not a bug, this is a feature

**Visible Confusion**

**Comment by urnotnick** [comment]
it looked cooler in my head than it actually does, its being removed in the next update

however this is not a bug
