### ISSUE TITLE
Normal Buttons not working

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#27]
**Describe the bug**
Normal buttons don't work, it says that I already have max buttons.

**To reproduce**
Steps to reproduce the behaviour:
1. Get the button tool
2. Spawn a button
3. See error

**Expected behaviour**
you should be able to spawn buttons

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
No lua error

**Additional context**
pls fix

**Comment by urnotnick** [comment]
not a bug, max buttons is 0
