### ISSUE TITLE
Vortessence going through shackles

### ISSUE THREAD

**Issue by Astrroo** [urnotnick/impulse-issues#29]
**Describe the bug**
Per the title, using vortessence while shackled will deshackle you and allow you to use the powers/gain legal esp.

**To reproduce**
Steps to reproduce the behaviour:
1. Be a vort
2. Be shackled
3. Use vortessence

**Expected behaviour**
That it'll not allow me to use it.

**Screenshots**
https://medal.tv/games/garrys-mod/clips/7VieeJZBz6DJ-/d13376XQVEc4?invite=cr-MSxvc0EsMTUxMTkxODcs

**impulse version (press F1 in the bottom right):**
1.9.0

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by urnotnick** [comment]
fixed
