### ISSUE TITLE
E2 - HoloAnim / WireExtras

### ISSUE THREAD

**Issue by Edgarssimsons** [urnotnick/impulse-issues#3]
**Describe the bug**
Unlike Impulse, the server has no access to the HoloAnim() functionality included in WireExtras Extension.
This function is crucial for many E2's created on impulse to work properly, it allows e2's to use existing animations of all props that have them (When they are HOLOS). 

**impulse version (press F1 in the bottom right):**
1.8.1

**E2 Code**
holoAnim(1,2,0.1) 

**Lua error**
No such function: holoAnim(number, number, number) at line 16, char 9

**Additional context**

**Comment by BorealBlizzard** [comment]
I second this

**Comment by urnotnick** [comment]
Wire Extras will come in the next update, however this is not a bug.
