### ISSUE TITLE
Human through ca letter chute

### ISSUE THREAD

**Issue by JudgeDragon** [urnotnick/impulse-issues#30]
**Describe the bug**
Using the letter chute in the nexus you can fit someone through it using a precision tool and a chair

**To reproduce**
Steps to reproduce the behaviour:
1. Go to nexus lobby
2. Spawn vehicle chair
3. Sit a partner on it
4. Use the precision tool to get it in
5. Use the phsgun the unfreeze it

**Expected behaviour**
Should send you into the ca office with the chair but from their i know nothing

**Comment by xSovietBear** [comment]
Not a bug with of the server. It's more like of chair abuse and misusing the letter chute which already against the server rules

**Comment by Astrroo** [comment]
Its an abuse with the filtering system built into the map, per Soviet it's already against server rules.

**Comment by urnotnick** [comment]
Not an issue with framework or schema
