### ISSUE TITLE
Grizzly Grotto vent lock kinda broken

### ISSUE THREAD

**Issue by BorealBlizzard** [urnotnick/impulse-issues#31]
**Describe the bug**
The locking lever for the Grizzly Grotto vent lever doesn't rotate at the hinge correctly.

**To reproduce**
Go to the Grotto and press E on the lever under the work table

**Expected behaviour**
Lever should bend at the hinge, it instead bends at the midpoint of the 

**Screenshots**
https://imgur.com/a/sSZ8kRy

**impulse version (press F1 in the bottom right):**
np_industrial17_landis version 1
**Lua error**
N/A

**Additional context**
Minor map issue, the vent works perfectly fine its just the lever thats wonky

**Comment by Astrroo** [comment]
Map issue, not a server issue. Also, this has already been acknowledged though isn't entirely game-breaking, I'd expect a fix whenever an update comes through though don't hold your breath.

**Comment by BorealBlizzard** [comment]
Cool, just wanted to point it out. Also may there should be a tag or forums section for map related issues? Anyway ill just close this now.
