### ISSUE TITLE
Scanner Issue 

### ISSUE THREAD

**Issue by TheBeanyBean** [urnotnick/impulse-issues#32]
Whenever I click E to scan someone nothing happens except a small window appearing on the right side of my screen titled "Window"

As a scanner all I did was click E to scan someone and it happened 

From what an admin said it was supposed to turn the Unknown tag "Which there was non" into a name 

https://imgur.com/a/JuxHn17

1.9.2

No Lua Errors made

No Extra context it just kinda started happening

**Comment by urnotnick** [comment]
ah this was something I forgot to finish with 1.9.2, will patch ASAP

**Comment by urnotnick** [comment]
fixed
