### ISSUE TITLE
357 scrapping issue

### ISSUE THREAD

**Issue by NforceSSP** [urnotnick/impulse-issues#33]
**Describe the bug**
The broken .357 says that it requires level 5 to scrap, however at level 5, you are still not able to scrap it.
**To reproduce**
Steps to reproduce the behaviour:
1. Get a broken .357
2. Have at least scrapping level 5
3. Attempt to scrap the broken .357

**Expected behaviour**
The .357 is scrapped.
**Screenshots**
[https://youtu.be/Zwu-bGk6Kts](url)

**impulse version (press F1 in the bottom right):** 1.9.2

**Comment by NforceSSP** [comment]
This bug also pertains to the shotgun

**Comment by ICooki3zI** [comment]
Fixed, no issue with the spas.
