### ISSUE TITLE
Breaching charges

### ISSUE THREAD

**Issue by SpriteCran** [urnotnick/impulse-issues#34]
**Describe the bug**
Breaching charges don't work on apartment doors.

**To reproduce**
Steps to reproduce the behaviour:
1. Go OTA.
2. Go to apartment block.
3. Plant breaching charge on door.
4. Receive error.

**Expected behaviour**
Normally, door would get blown off.

**Screenshots**
https://medal.tv/games/garrys-mod/clips/8ugfGzSRFdR43/d1337H7lH7C1?invite=cr-MSxucGQsMTE3NTU5MjYs

**impulse version (press F1 in the bottom right):**
1.9.2
**Lua error**
'[ERROR] gamemodes/landis-hl2rp/schema/items/sh_item_breachingcharge.lua:160: attempt to call method 'IsApartmentDoor' (a nil value)
  1. ShouldTraceUse - gamemodes/landis-hl2rp/schema/items/sh_item_breachingcharge.lua:160
   2. unknown - gamemodes/impulse/gamemode/core/vgui/cl_inventoryitem.lua:242'

**Additional context**
BITCH

**Comment by Astrroo** [comment]
Fixed.
