### ISSUE TITLE
Prisoner Spawning

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#35]
**Describe the bug**
When this bug occurs all prisoners spawn only in cell 1 instead of getting random assigned cells.

**To reproduce**
It occurs at random after some prisoners go through the prison.

**Expected behaviour**
Prisoners should spawn in all cells, not just cell 1.

**Impulse version**
1.9.2

**Comment by urnotnick** [comment]
There's 1 prison spawn point, don't know what you are getting at here but everything works as designed.

**Comment by NICKOLAS78GR** [comment]
One? back in impulse there where multiple, if you check the conv.index on a terminal you'll see it evens says "ASSIGNED CELL"

**Comment by NICKOLAS78GR** [comment]
Hey @urnotnick , better check the D47 config, maybe see the multiple prison spawnpoints Vingard placed
