### ISSUE TITLE
You can't close the whitelist menu.

### ISSUE THREAD

**Issue by C0nArtist** [urnotnick/impulse-issues#36]
**To reproduce**
Steps to reproduce the behaviour:
1. Go to any profile on the scoreboard.
2. Click on Show whitelists
3. You can no longer close out of the thing, and you can't even access your GMOD menu.

**Expected behaviour**
The whitelist shower to close lol

**Screenshots**
(you can see the gmod background is blurred, which means i can't access it)
![image_2022-02-06_201213](https://user-images.githubusercontent.com/99154608/152714150-fd4b87b6-baa8-4f6f-9c18-25fc61d24db4.png)

**impulse version (press F1 in the bottom right):**

Impulse 1.9.2

**Comment by urnotnick** [comment]
This is from what I see an issue with Derma_Message, something I cannot fix really.

Just don't press escape when viewing whitelists.
