### ISSUE TITLE
OTA Promotions broken.

### ISSUE THREAD

**Issue by buffingtonpp** [urnotnick/impulse-issues#37]
**Describe the bug**
As Overwatch when I first open the F6 menu I have the promotions option, few minutes later I reopen the F6 menu and it's gone meaning the PRMT and DEMOTE thing arent there.

**To reproduce**
Steps to reproduce the behaviour:
1. OPEN PDA, PRMT IS THERE
2. OPEN IT 5 min later
3. See error

**Expected behaviour**
The PRMT option stays there

**impulse version (press F1 in the bottom right):**

1.9.2

**Lua error**

[ERROR] gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447: attempt to call method 'GetPropertyOwner' (a nil value)
  1. SetupPDA - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447
   2. Init - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:15
    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
     4. v - gamemodes/landis-hl2rp/plugins/dispatch/cl_hooks.lua:3
      5. Run - lua/includes/modules/hook.lua:96
       6. unknown - gamemodes/impulse/gamemode/core/hooks/cl_hooks.lua:77

**Comment by urnotnick** [comment]
Investigating this today

**Comment by fatnigggersex3432** [comment]
nigger furry porn

**Comment by fatnigggersex3432** [comment]
yo larson i am in your pc btw this is bob murder speaking

nice night in the woods rule34 shit dam ;)

**Comment by fatnigggersex3432** [comment]
YO STOP DELETING MY SHIT YOU NAZI ROLEPLAYER CUNT

LARSON I WILL RAPE U ASS HOLE

**Comment by fatnigggersex3432** [comment]
YO STOP DELETING MY SHIT YOU NAZI ROLEPLAYER CUNT

LARSON I WILL RAPE U ASS HOLE

**Comment by fatnigggersex3432** [comment]
LOOOOOL HE MAAD MADD

**Comment by fatnigggersex3432** [comment]
LARSON GET YO ASS BACK TO THE DEGNERATE NEO NAZI DISCORDS YOU SICK FUCK, STOP WATCHING CHILD PORN
