### ISSUE TITLE
Molotov Cocktail not being in the correct crafting bench

### ISSUE THREAD

**Issue by DonSom3a** [urnotnick/impulse-issues#39]
**Describe the bug**
The Molotov item should not be in the General Workbench, it should be in the Weaponsmithing Bench as it needs a weaponsmithing level of 4, not a crafting level.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to General Workbench
2. Scroll down to 'Molotov Cocktail'
3. See error

**Expected behaviour**
I expected that the Molotov could be crafted with a crafting level of 4, since it was in the general workbench. But I asked in OOC chat, and they told me it should be weaponsmithing.

**Screenshots**
I don't have any screenshots since the server is down for an ISP migration, but I'm pretty sure the version is 1.9.2 right now

**Lua error**
None

**Additional context**
None

**Comment by X-Mezo-X** [comment]
To be fair, a molotov shouldn't be considered something to require weaponsmithing skill, it's just a bottle filled with flammable alcohol and cloth, nothing as complex as making a weapon, the fix here should be in having the molotov be compatible with the Crafting skill and not the weaponsmithing skill.. a molotov is surely a weapon, but it's not a complex one to require knowledge in fabricating guns..

**Comment by NforceSSP** [comment]
> To be fair, a molotov shouldn't be considered something to require weaponsmithing skill, it's just a bottle filled with flammable alcohol and cloth, nothing as complex as making a gun, the fix here should be in having the molotov be compatible with the Crafting skill and not the weaponsmithing skill.. a molotov is surely a weapon, but it's not a complex one to require knowledge in fabricating guns.. 

that's not fixing the bug thats a suggestion

**Comment by fatnigggersex3432** [comment]
nick more like nigggger haha want some furry porn hit me up on discord at McMalice#0452

**Comment by urnotnick** [comment]
Fixed in 1.10.0
