### ISSUE TITLE
Wire - Vehicle Controller is stuck as ghosted

### ISSUE THREAD

**Issue by BorealBlizzard** [urnotnick/impulse-issues#4]
**Describe the bug**
Wire - Vehicle Controller is stuck as ghosted

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'wire>vehicle control'
2. Click on 'Vehicle Controller'
3. Spawn one
4. Try to unghost it

**Expected behavior**
Should not longer be ghosted after freezing it using the physgun

**Screenshots**
https://i.imgur.com/lKhMeaW.jpg

**impulse version (press F1 in the bottom right):** 1.8.1

**Lua error**
N/A

**Additional context**
Im trying to use it along side Vehicle Exit points to make usable Bar-stools in the grotto

**Comment by BorealBlizzard** [comment]
no updates? cool

**Comment by urnotnick** [comment]
i've been working on other fixes, there were like 13 fixes in 1.9 and sadly this random entity getting ghosted couldn't get in.

I'm not sure what causes this tbh, but i'll investigate it in time.

**Comment by BorealBlizzard** [comment]
Just being facetious, thanks though.

**Comment by urnotnick** [comment]
this is either a 1 off thing or just a random wire issue. Either way, nothing I can do to fix this
