### ISSUE TITLE
Weapon belt for all roles

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#41]
**Describe the bug**
All roles show weapons that are available for CP's to CP weapon belt positions despite the fact that they are not supposed to be there

**To reproduce**
Go OTA, select Echo OWS, see smg appear inside the waist
Go OTA, select Mace, see the spac 12 appear in your vest
Go CWU, equip a pistol, see pistol float next yo your pants

**Expected behaviour**
All those instances above should not be happening

**impulse version (press F1 in the bottom right):**
1.9.2

**Comment by urnotnick** [comment]
this isnt a bug

**Comment by NICKOLAS78GR** [comment]
@urnotnick  If that is clearly indented I have a few questions;

![image](https://user-images.githubusercontent.com/81629850/156813050-322151cc-819d-4868-9dfd-2d6f4605b486.png)
![image](https://user-images.githubusercontent.com/81629850/156813061-725a8745-3ebc-4b2f-8f6a-f879480d1576.png)
Why is the pistol clipping inside the hand and floating?

![Garry's Mod 2022 03 04 - 19 15 05 05 DVR_Moment(2)](https://user-images.githubusercontent.com/81629850/156813651-399afe18-3471-4ced-b063-8db63f5fd797.jpg)
![Garry's Mod 2022 03 04 - 19 17 14 06 DVR_Moment](https://user-images.githubusercontent.com/81629850/156813698-23cc2fdf-d95e-45b4-8307-43bafb02bbca.jpg)
Why are the OTA weapons phasing through them?


And most importantly, https://cdn.discordapp.com/attachments/840308016788275210/949357281831694446/Garrys_Mod_2022.03.04_-_19.19.16.07.DVR_Trim.mp4
If it isn't a bug but instead an intended feature, why isn't that the case for the AR2?



My opinion? You just copied and pasted the CP weapon belt system creating all those visual artifacts.
