### ISSUE TITLE
Making a F3 when there are no staff on

### ISSUE THREAD

**Issue by Neshachenus** [urnotnick/impulse-issues#43]
**Describe the bug**
A clear and concise description of what the bug is. when you make an F3 it tells you to go to the impulse forums instead of Landis forums

**To reproduce**
Steps to reproduce the behaviour:
1. Go to F3 ticket
2. Click on make a ticket
4. See error 'says since there is no staff on go to impulse forums'

**Expected behaviour**
A clear and concise description of what you expected to happen. Just says impulse forums 

**Screenshots**

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by urnotnick** [comment]
Fixed in 1.10, will most likely push a silent patch correcting this.
