### ISSUE TITLE
Music Kit not playing - says files are missing

### ISSUE THREAD

**Issue by er1cw05** [urnotnick/impulse-issues#44]
**Describe the Bug**
When you enter the game and press the play button with a newly made Music Kit, the console will say the file is missing in the sound folder when it clearly isn't.

**To reproduce**
1. Open Sound
2. Put a new .mp3 in (recommended in a folder of your choosing).
3. Go to garrysmod/data/impulse/musickits and make a new .json file in this location.
4. Follow the Music Kit creation guide to code it.
5. Enter the game.
6. Go into console and type 'impulse_music_debug 1'.
7. Press Play.
8. Look in console.
9. Result.

**Expected Behavior**
The music should play correctly and no error should be coming up.

**Screenshots**
![image](https://user-images.githubusercontent.com/60023945/159091533-7009ffbc-9390-4a12-9381-7bb8bbe9b80d.png)
![image](https://user-images.githubusercontent.com/60023945/159091554-b7aa0608-9487-4d1b-94b3-56e762795dbb.png)

**Lua Error**
Failed to load sound "tfd\ambient\scp original astowo  the bookburners theme of the ungoc.mp3", file probably missing from disk/repository
- This error varies depending on the song itself.

**Comment by Astrroo** [comment]
From my knowledge, this issue isn't the fault of the framework or game server. Try renaming all of your mp3s to have underscores instead of spaces then reflect that in your json, this the likely issue.

**Comment by er1cw05** [comment]
I'll try that and update you if it fixes it.

**Comment by er1cw05** [comment]
> From my knowledge, this issue isn't the fault of the framework or game server. Try renaming all of your mp3s to have underscores instead of spaces then reflect that in your json, this the likely issue.

This works.
