### ISSUE TITLE
Wrong unban URL

### ISSUE THREAD

**Issue by Chosen-Marsh** [urnotnick/impulse-issues#45]
**Describe the bug**
Wrong link

**To reproduce**
Steps to reproduce the behaviour:
1. Get banned
2. See the mistake 

**Screenshots**
https://cdn.discordapp.com/attachments/917452949117091853/954809756688719933/unknown.png

**impulse version (press F1 in the bottom right):**
1.9.2

**Comment by urnotnick** [comment]
Not a framework or a schema issue, but still fixed regardless
