### ISSUE TITLE
Another Lua Error From Me, but Different (idfk how to title these???)

### ISSUE THREAD

**Issue by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [urnotnick/impulse-issues#48]
Heyy, back with another Lua Error, but this time it seems to have something to do with the little terminals outside ownable properties like apartments or stores. When I tried to get info as CP, this error log popped up

gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447: attempt to call method 'GetPropertyOwner' (a nil value)
    1. SetupPDA - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:447
        2. Init - gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:15
            3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
                4. v - gamemodes/landis-hl2rp/plugins/dispatch/cl_hooks.lua:3
                    5. Run - lua/includes/modules/hook.lua:96
                        6. unknown - gamemodes/impulse/gamemode/core/hooks/cl_hooks.lua:77
                        
Again, not really sure what's the problem, I'm no coder, so idk lol

**Comment by Astrroo** [comment]
Not enough information after 3 months. Closing inactive thread.
