### ISSUE TITLE
Bug with my gun's muzzle

### ISSUE THREAD

**Issue by Bilioss** [urnotnick/impulse-issues#51]
**Describe the bug:**
Whenever I shoot my SMG, USP or any other gun in _first person_ I see an ugly muzzle in the front of my gun. It blocks my view when I use the zoom in with right click.

**Impulse version:**
Most recent one (1.10) and previous.

https://user-images.githubusercontent.com/103890597/163719137-fe21b774-df5c-4886-a44a-116d1be51f5d.mp4

**Comment by urnotnick** [comment]
This is a clientside issue, nothing from our content or anything is causing this
