### ISSUE TITLE
Scope for Mosin Nagant

### ISSUE THREAD

**Issue by AlyxV1** [urnotnick/impulse-issues#52]
When equipping the Hunting Scope for the Mosin Nagant, you actually zoom out and the Scope isn't attached to the rifle.
![20220417170057_1](https://user-images.githubusercontent.com/103899411/163727743-852dc9b1-98f0-4bb0-83d8-51e91b32a5cb.jpg)
![20220417192345_1](https://user-images.githubusercontent.com/103899411/163727746-a28a3454-e653-4025-a5a0-c838f09e5a53.jpg)
![20220417192348_1](https://user-images.githubusercontent.com/103899411/163727747-8c7f2b27-115a-4e3e-b54a-618ea82a8011.jpg)
![unknown (1)](https://user-images.githubusercontent.com/103899411/163727749-0ab5e294-0358-4103-a658-9541126c5e54.png)

**Comment by urnotnick** [comment]
There wasn't meant to be a scope for the mosin yet.
