### ISSUE TITLE
impulse_cameratoggle

### ISSUE THREAD

**Issue by SpriteCran** [urnotnick/impulse-issues#53]
**Describe the bug**
impulse_cameratoggle completely breaks your game.

**To reproduce**
Steps to reproduce the behaviour:
Open the console
Type "impulse_cameratoggle"
Try to open chat; you'll notice that your GUI hasn't disappeared.
Type it again to try and undo
Rejoin because you can't fix it w/o rejoining

**Expected behaviour**
Impulse_cameratoggle is, as you know, used to take, like, screenshots and shit without having the HUD get in the way. 
UNFORTUNATELY, it no longer works. The HUD remains on your screen, you can't open chat, and you can't undo it.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.10.1

**Lua error**
N/A

**Additional context**
It may or may not help/have broken due to the fact that I had longsword_debug ON at the time.

**Comment by ICooki3zI** [comment]
Had no issues testing this with and without longsword debug on.
