### ISSUE TITLE
.357 Ironsights are off-set

### ISSUE THREAD

**Issue by zachun** [urnotnick/impulse-issues#54]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Get a .357
2. Hold RMB
3. Have an addon that replaces our crosshair, boom
4. See the issue

**Expected behaviour**
Ironsight fucked up

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/854587601045291018/966014249547731024/unknown.png)

**impulse version (press F1 in the bottom right):**
1.10.1

**Lua error**
N/A

**Additional context**
N/A

**Comment by urnotnick** [comment]
this is called sway.
![image](https://user-images.githubusercontent.com/66189083/164055942-a963a3c8-c5b9-475a-863e-6aa1c94c9634.png)
