### ISSUE TITLE
Ragdolls causing Server Crashes

### ISSUE THREAD

**Issue by UniversalArchitect** [urnotnick/impulse-issues#56]
**Describe the bug**
Taking and holding a ragdoll then getting teleported across the map (e.g from sewers to outlands quadrant 2) causes the server to crash
People are starting to find out about it so I've decided to report it.

**To reproduce**
Steps to reproduce the behaviour:
Take a ragdoll
Go somewhere where you get teleported from a certain area of the map to another with the ragdoll
Go through
Server crashes

**Expected behaviour**
Maybe ragdolls should be unable to be dragged through map teleports

**Screenshots**
Can't provide any, I don't wanna crash the server just to prove it

**impulse version (press F1 in the bottom right):**
![image](https://user-images.githubusercontent.com/76706139/164128914-79fdd057-95a9-489d-9632-e40534d5bbed.png)

**Lua error**
If applicable, post the error here in full.
Unable to do so
**Additional context**
None

**Comment by Astrroo** [comment]
I am unsure if Nick can fix this issue please correct me if I’m wrong. However, as a primitive solution I could attempt at fixing it on my end by adding a filtering system.

**Comment by urnotnick** [comment]
fixed
