### ISSUE TITLE
Main Menü "Credits" makes you become stuck

### ISSUE THREAD

**Issue by Askastaa** [urnotnick/impulse-issues#58]
**Describe the bug**
When you press "Credits" in the Main Menü ingame and let it do its starwars intro thing, it will bring you back to the main menü but it wont show any text and makes you become stuck

**To reproduce**
Steps to reproduce the behaviour:
1. Press "Credits" on Main Menü
2. Let it do its starwars thingy
3. Boom you are offically stuck
4. No Console Errors

**Expected behaviour**
To make it bring you to main menü back without forcng you to rejoin cause u stuck.

**Screenshots**
https://cdn.discordapp.com/attachments/967866086697599066/967870713753137222/unknown.png

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by ICooki3zI** [comment]
The credits button doesn't exist anymore
