### ISSUE TITLE
CP/OTA remain on doors

### ISSUE THREAD

**Issue by SymKelp** [urnotnick/impulse-issues#6]
**Describe the bug**
When you add someone to your door, and they change faction to CP/OTA, they remain on your door and cannot be manually removed via the terminal.

**To reproduce**
Steps to reproduce the behaviour:
1. Add player to door via terminal
2. Said player changes faction to CP/OTA
3. Remains on the door

**Expected behaviour**
I would expect the faction-swapping player to automatically be removed, or to have an option directly in the list to remove from the door. Since CP/OTA characters are not added to the list, you cannot go in and remove their access.

**Additional context**
Suggested fix is either auto removing the player, or adding the button to remove next to the player's name, rather than in the upper dropdown box.

**Comment by urnotnick** [comment]
Patched in 1.9.0
