### ISSUE TITLE
Pistol has not reload sound and is not the mmod one

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#63]
**Describe the bug**
Pistol has not reload sound and is not the mmod one

**To reproduce**
Have the indented server content and use a pistol on the server, you'll see that the pistol in NOT the mmod one but this https://steamcommunity.com/sharedfiles/filedetails/?id=1644171575
which is in the impulse content. Additionally, there are no reload sounds.

**Expected behaviour**
The pistol replacement that is in https://steamcommunity.com/sharedfiles/filedetails/?id=1689357640 shall get removed,
contact vin to remove it or create a Landis version if the impulse content packs, that way implement the mmod pistol correctly. 

**Video**
https://cdn.discordapp.com/attachments/917452949117091853/970377442202120252/BAD_BAD_REALLY_BAD.mp4

**impulse version (press F1 in the bottom right):**
1.10.3

**Comment by Astrroo** [comment]
Not an issue.
