### ISSUE TITLE
Weapon sounds

### ISSUE THREAD

**Issue by Syadiya224** [urnotnick/impulse-issues#64]
Pistol and SMG do not have any reload sounds 

(Optional) Get a weapon sound replacer
Apply Landis content
Go into single-player or on the server
No reload sounds

Weapons use the weapon sound replacer's sound files - or at least have reload sounds

(No applicable screenshots)

1.10.3

**Comment by X-Mezo-X** [comment]
It's because the lua files of the mmod content included in the Landis content has some default sounds muted, including the reload sounds of those two weapons.

**Comment by Astrroo** [comment]
Not an issue.
