### ISSUE TITLE
Wrong Scanner Spawn position

### ISSUE THREAD

**Issue by avxsb** [urnotnick/impulse-issues#68]
**Describe the bug**
Scanners are spawned in the void

**To reproduce**
Steps to reproduce the behaviour:
1. Go DEFENDER
2. Deploy Scanner
3. See error

**Expected behaviour**
Scanners should be spawned somewhere where they can patrol the city

**Screenshots**
https://cdn.discordapp.com/attachments/973619488903798804/978416403424108614/unknown.png

**impulse version (press F1 in the bottom right):**
1.10.4

**Lua error**
no

**Additional context**
Credits to Santos for finding this

**Comment by Astrroo** [comment]
Fixed map issue.
