### ISSUE TITLE
Apartment Containers Not Working

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#69]
**Describe the bug**
Storage lockers in Apartment Block C not working when you own the apartment it's in.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Apartment Block C on Toitsu Street
2. Purchase any apartment in the block (for me it happened on the second floor specifically, just assuming it's the same for others)
3. Attempt to access the provided storage container
4. Notice that it says you cannot use this container

**Expected behaviour**
That you're able to access the storage container in your apartment like every other apartment

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.10.4

**Lua error**
If applicable, post the error here in full.
N/A
**Additional context**

**Comment by urnotnick** [comment]
Fixed
