### ISSUE TITLE
Laundry Duplication

### ISSUE THREAD

**Issue by Astrroo** [urnotnick/impulse-issues#7]
**Describe the bug**
Laundry can duplicate itself when put into two washers at the same time.

**To reproduce**
Steps to reproduce the behaviour:
1. Get dirty laundry
2. Press it against two close together washing machines

**Expected behaviour**
One of the laundry machines would take the piece of laundry, not both.

**Screenshots**
https://medal.tv/games/garrys-mod/clips/7cTXWhh6ZlhhO/d1337z2OM30J?invite=cr-MSw1ejksMTUxMTkxODcs

**impulse version (press F1 in the bottom right):**
1.8.1

**Lua error**
N/A

**Additional context**

**Comment by Chosen-Marsh** [comment]
This was an Issue before Landis an easy fix would be just to move the laundry machine apart from each other.

**Comment by urnotnick** [comment]
> This was an Issue before Landis an easy fix would be just to move the laundry machine apart from each other.

this is the only real fix, the issue roots from two collisions being detected at the same tick, making it (to my knowledge) impossible to distinguish

**Comment by urnotnick** [comment]
moved laundry further apart, no real other fix.
