### ISSUE TITLE
KATO CAFE Storage box not working properly

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#70]
**Describe the bug**
The KATA CAFE Storage box is inaccessible to the owner

**To reproduce**
Buy KATO CAFE, open the container, see message that you cannot open it

**Expected behaviour**
The storage box should be accessible to the owner

**impulse version (press F1 in the bottom right):**
1.10.4

**Comment by urnotnick** [comment]
Fixed
