### ISSUE TITLE
L1 Access Doors Openable by Citizens

### ISSUE THREAD

**Issue by shanguoman** [urnotnick/impulse-issues#71]
**Describe the bug**
The L1 access doors next to the Nexus blast door are openable by citizens.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to both L1 access doors by the Nexus blast door
2. Press E on the doors
4. They will open

**Expected behaviour**
Citizens should be unable to open L1 access doors.

**impulse version (press F1 in the bottom right):** 1.10.4

**Additional context**
I do not know for certain if this happens with other UU access doors, these were the only ones I can easily reach.

**Comment by Astrroo** [comment]
Map issue

**Comment by Astrroo** [comment]
Fixed map issue.
