### ISSUE TITLE
Building can not be purchased

### ISSUE THREAD

**Issue by TomRistpt1** [urnotnick/impulse-issues#72]
**Describe the bug**
When you buy this building, the money is taken away from you, you pay it. But, you dont get access/keys for the building 

**Expected behaviour**
When buying the building, you would get the keys for it

**Screenshots**
https://imgur.com/a/Xc5u3t7

**impulse version (press F1 in the bottom right):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by urnotnick** [comment]
Fixed
