### ISSUE TITLE
Apartment Block-C room 201 chest

### ISSUE THREAD

**Issue by SamanthaDoesShit** [urnotnick/impulse-issues#73]
**Describe the bug**
The Storage Box in apartment 201 of Block C (City 8) is bugged and does not let the owner of the room access it.
**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'Apartment Block-C, Room 201'
2. Buy the room.
3. Hit E on the room's Storage Container

**Expected behaviour**
Opening the Storage Container

**impulse version (press F1 in the bottom right):**
Whatever the version is as of 6/6/2022

**Lua error**
(unneeded)

**Additional context**
Kinda slightly a little annoying

**Comment by urnotnick** [comment]
Fixed
