### ISSUE TITLE
PDA doesn't update when pressing buttons, attempt to call method 'GetPropertyOwner' (a nil value)

### ISSUE THREAD

**Issue by karl-police** [urnotnick/impulse-issues#74]
**Describe the bug**
PDA doesn't update when pressing buttons, attempt to call method 'GetPropertyOwner' (a nil value).

I don't know how this happens. The error would re-appear everytime when I press F6.

If I interact with the buttons to join a PT and etc. it doesn't immediately update the UI, instead I have to close the PDA window and open it again to see a change. This issue is only when that error appears.

**To reproduce**
Steps to reproduce the behaviour:
1. Unsure, how this issue is caused.
2. You are a ranked CP i4 - i1.
3. You press F6 while that bug is active, each time you press F6 that error appears.

**Expected behaviour**
Able to normally open F6 and interact with buttons on the PT page and it updating the UI when pressing on the button. So, when you press LEAVE that it would update you not being in the PT anymore on the UI.

**Screenshots**
-

**Lua error**
``[ERROR] gamemodes/landis-hl2rp/plugins/dispatch/vgui/cl_pda.lua:459: attempt to call method 'GetPropertyOwner' (a nil value)``

**Additional context**
-

**Comment by ICooki3zI** [comment]
Don't have this issue on the main server. Might just be an issue when no one has an apartment.

**Comment by sophfee** [comment]
patched
