### ISSUE TITLE
Loading ammo into nothing

### ISSUE THREAD

**Issue by dpbrown04** [urnotnick/impulse-issues#75]
**Describe the bug**
For some reason I was able to load ammo into the void

**To reproduce**
1. Go to player inventory
2. Click on the ammo then click on load

**Expected behavior**
I don't expect much but if I get a response saying "WeLl dOn'T cLiCk On LoAd" then that's just a lazy response

**Comment by X-Mezo-X** [comment]
You don't actually load ammo into nothing, it adds the loaded ammo to your reserve, so once you pull out a weapon (provided that you didn't die or get arrested prior to doing that), you'll find the loaded amount in your reserve ammo.

**Comment by Astrroo** [comment]
Not an issue.
