### ISSUE TITLE
Avalon Venue being broken

### ISSUE THREAD

**Issue by NICKOLAS78GR** [urnotnick/impulse-issues#76]
**Describe the bug**
When Avalon Venue is bought, the owner can't interact with the door, access the container and even open the windows

**Expected behaviour**
 Access to the doors and the container of the store should be accessible to the owner
**Screenshots**

**impulse version (press F1 in the bottom right):**
1.10.4

**Additional context**
https://media.discordapp.net/attachments/918781424457367582/987372831853658182/20220617180456_1.jpg?width=1026&height=577
Also the text for the windows floats in the middle of the room

**Comment by urnotnick** [comment]
Fixed
