### ISSUE TITLE
OTA Compass working incorrectly

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#78]
**Describe the bug**
The HUD compass that all OTA soldiers get works incorrectly, it displays the directions wrong. When looking in the direction of Northern Outlands it shows them as East, for example. This creates a lot of confusion when sweeping the outlands as OTA.

**To reproduce**
1. Join as OTA
2. Go to outlands
3. Look in the direction of Northern/Western/Eastern outlands
4. Look at your HUD compass and see that it displays you the wrong cardinal direction.

**Expected behaviour**
Northern Outlands should be in the North, Western Outlands should be in the West, and so on.

**Screenshots**
![image](https://user-images.githubusercontent.com/47142477/175632645-7dfda8e9-96bb-43f0-9ac3-ab493ac2b6c5.png)

**impulse version (press F1 in the bottom right):**
1.10.6

**Lua error**
-

**Additional context**
-

**Comment by Astrroo** [comment]
Config issue for a previous map. Fixed anyways.
