### ISSUE TITLE
Flashbang bug

### ISSUE THREAD

**Issue by xSovietBear** [urnotnick/impulse-issues#8]
**Describe the bug**
Flashbang can go through walls

**To reproduce**
Steps to reproduce the behaviour:
1. Get a flashbang
2. Throw it in a room you are outside
3. Wait for bang

**Expected behaviour**
You shouldn't be fully flashed

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/925419667122688042/929377774412632104/unknown.png
https://cdn.discordapp.com/attachments/925419667122688042/929377803701456896/unknown.png
https://cdn.discordapp.com/attachments/925419667122688042/929377814602452992/unknown.png)

**impulse version (press F1 in the bottom right):**
1.8.1

**Lua error**
None

**Additional context**
plz fix

**Comment by urnotnick** [comment]
Fixed in 1.9.0
