### ISSUE TITLE
new update bug

### ISSUE THREAD

**Issue by Apollo12325** [urnotnick/impulse-issues#85]
**headcrabs wont be chopped up**

**To reproduce**
Steps to reproduce the behaviour:
1. find headcrab with cleaver
2. open inventory and click cleaver while looking at headcrab

**soon fixed**

**Screenshots**

**impulse version (press F1 in the bottom right):**
f1
**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by Astrroo** [comment]
Not a framework or schema issue. A server convar needs to be modified.
