### ISSUE TITLE
Improperly Configured Storage Boxes

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#86]
**Describe the bug**
Storage boxes that are located inside certain apartments are not linked to ownership of that apartment, meaning if I were to own apartment 101, the storage box inside will be inaccessible to me.

**To reproduce**
Steps to reproduce the behaviour:
1. Purchase an apartment with a storage box inside (in my case, Apartment 101)
2. Attempt to access it's storage box
3. Observe how the game will not let you access the box

**Expected behaviour**
That the storage box will allow you access to it when owning the corresponding apartment.

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/1749105694374859413/D31B182BE1904C1AD37E13BCD09C3E7F8F45A03D/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

https://steamuserimages-a.akamaihd.net/ugc/1749105694374859856/011C2F658D37F5FF667F1744A179234CA1CEF7EF/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

https://steamuserimages-a.akamaihd.net/ugc/1749105694374860247/51A0B97E2724E3B3CACDB34D3F7024131BA77A85/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**impulse version (press F1 in the bottom right):**
1.10.8

**Lua error**
N/A

**Additional context**
N/A

**Comment by Astrroo** [comment]
Should've been fixed in next patch.
