### ISSUE TITLE
OTA suit armor bug

### ISSUE THREAD

**Issue by CornOfTheFiles** [urnotnick/impulse-issues#9]
**Describe the bug**
Getting your rank as OTA, then switching off makes you keep your HEV suit armor.

**To reproduce**
Steps to reproduce the behaviour:
1. Get on OTA
2. Get your rank
3. Get your suit charge
4. Switch off of OTA

**Expected behaviour**
You keep all of your HEV suit armor, making you very tanky as a citizen/rebel.

**Screenshots**
-

**impulse version (press F1 in the bottom right):**
-

**Lua error**
-

**Additional context**
Switching classes (as CWU) or getting your rank as CP removes the bug.

**Comment by urnotnick** [comment]
framework issue, not hl2rp bug

**Comment by urnotnick** [comment]
patched in 1.10.0
