### ISSUE TITLE
Outdated tip in the loading screen

### ISSUE THREAD

**Issue by elrobusto** [urnotnick/impulse-issues#92]
**Describe the bug**
This tip is outdated because you can now salvage AR2s from dead OTA.

**To reproduce**
Steps to reproduce the behaviour:
1. Connect to the server
2. Look at the loading screen
3. Wait until the AR2 tip shows up

**Expected behaviour**
The outdated tip is not supposed to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/47142477/189222102-07f77ca7-7e4c-4fe4-8a19-ec2ebd787bab.png)

**impulse version (press F1 in the bottom right):**
1.10.8

**Comment by Astrroo** [comment]
- [ ] Not an issue for the framework or schema.
