### ISSUE TITLE
Our House Achievement Bug

### ISSUE THREAD

**Issue by TheZeroViper** [urnotnick/impulse-issues#95]
**Describe the bug**
Once you add the 9 people to your door, no achievement is gained. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to apartment
2. Buy apartment
3. Add 9+ people to door

**Expected behaviour**
You should receive the Our House achivement

**Screenshots**
None Taken

**impulse version (press F1 in the bottom right):**
Framework 1.11.0

**Comment by Astrroo** [comment]
The achievement is based off of buyable doors.
