### ISSUE TITLE
Soundscape Bug in Division 22 Train

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#96]
**Describe the bug**
When riding the train that connects District 47 and Division 22, instead of train moving noises, you will hear the annoyingly loud sounds of a bustling cityscape. Any attempt to stopsound will be futile, and you will hear these sounds until you disconnect and reconnect to the server again once you've activated them.

**To reproduce**
Steps to reproduce the behaviour:
1. Enter the train
2. Travel to Division 22 from D47 or vice versa.
3. Listen carefully for the sounds of a vast cityscape.

**Expected behaviour**
That when you ride the train, audio that actually sounds like a train barreling through a tunnel actually play, like how it is in the map on singeplayer.

**Screenshots**
Audio based issue, no need for screenshots.

**impulse version (press F1 in the bottom right):**
1.10.10

**Lua error**
N/A

**Additional context**
Seems like a similar issue to the C24 soundscapes, though I'm no programmer so these issues might be entirely different.

**Comment by Miraak11** [comment]
Update: Also happens when you enter the flooded area of the sewers, with all the cars and such floating around in the toxic goo.

**Comment by Miraak11** [comment]
Update: This happens at multiple points around the map. The issue is more widespread than initially anticipated.

**Comment by sophfee** [comment]
this is gmod shit, i'll look into this but it isn't high priority

**Comment by Miraak11** [comment]
This isn't relevant anymore since we've swapped to a map with working soundscapes, so I'll close it for now
