### ISSUE TITLE
HUD Vanishing

### ISSUE THREAD

**Issue by Miraak11** [urnotnick/impulse-issues#97]
**Describe the bug**A clear and concise description of what the bugug is.
When playing on the Combine faction, the HUD will randomly vanish and the console will be spammed with LUA errors. I will post the exact error in the appropriate section here.

**To reproduce**
Steps to reproduce the behaviour:
1. Join Combine Team
2. Play, maybe try switching divisions a couple times
3. See the problem

**Expected behaviour**
That the HUD doesn't disappear randomly during gameplay.

**Screenshots**
![20221001182530_1](https://user-images.githubusercontent.com/106186291/193430532-e2786828-a305-469c-b284-2cae10f0a3f9.jpg)

**impulse version (press F1 in the bottom right):**
1.10.10

**Lua error**
[ERROR] gamemodes/landis-hl2rp/plugins/combineoverlay/cl_overlay.lua:64: attempt to index field 'pos' (a nil value)
  1. DrawCombineWaypoints - gamemodes/landis-hl2rp/plugins/combineoverlay/cl_overlay.lua:64
   2. v - gamemodes/landis-hl2rp/plugins/combineoverlay/cl_overlay.lua:689
    3. unknown - lua/includes/modules/hook.lua:96 (x10)

**Additional context**
N/A

**Comment by sophfee** [comment]
should be patched
