### ISSUE TITLE
HL2RP DISTRICT 47 FORCEFIELD GLITCH

### ISSUE THREAD

**Issue by JerryBox12** [urnotnick/impulse-issues#98]
**Describe the bug**
Even though the forcefield is down, things you can pick up cannot pass through it.

**To reproduce**

UNSURE

**Expected behavior**
I do not know

**Screenshots**
(https://youtu.be/7QqfTbMujUc)

**version**
1.10.10

**Lua error**
N/A

**Additional context**

>

**Comment by sophfee** [comment]
Patches for this coming real soon, will test locally today as I've been working on a fix.
